print('Please enter your First Name: ')
x = input()
print('Text entered:', x)
print('Type:', type(x))
print('Please enter an integer value:')
x = input()
print('Please enter another integer value:')
y = input()
w, x, y, z = 10, 15, 20, 25
print(w, x, y, z)
print(w, x, y, z, sep=',')
print(w, x, y, z, sep='')
print(w, x, y, z, sep=':')
print(w, x, y, z, sep='-----')